version: '3.9'


networks:
  kafka-net:
    name: kafka-net
    driver: bridge


services:
  spring-boot-docker-demo:
    container_name: spring-boot-docker-demo-app
    build: .
    networks:
      - kafka-net
    restart: always
    ports:
      - "8081:8080"